#!/usr/bin/env bash
# ============================================================
# deploy-ui.sh <test|prod>
# ------------------------------------------------------------
# Deploys ui/ to THIS account's S3 + CloudFront. (This account has NO Amplify;
# Amplify lives on the company account. amplify.yml is the alternative for there.)
#
# Generates ui/scripts/env-config.js (the runtime API/Cognito config — the same
# thing amplify.yml would produce), syncs to the env's frontend bucket, and
# invalidates CloudFront. Needs only the aws CLI (no sam/zip) → runnable from
# Windows Git Bash, WSL, or AWS CloudShell.
#
#   bash scripts/deploy-ui.sh test
#   bash scripts/deploy-ui.sh prod
# Override defaults via env vars: API_BASE_URL=… COGNITO_CLIENT_ID=… COGNITO_HOSTED_UI_DOMAIN=…
# ============================================================
set -euo pipefail
STAGE="${1:?usage: deploy-ui.sh <test|prod>}"
REGION="${AWS_REGION:-ap-southeast-2}"

case "$STAGE" in
  prod)
    BUCKET="fieldsight-web-509194952652"
    CF_ID="E12IVML224YUEE"
    DEF_API="https://khfj3p1fkb.execute-api.${REGION}.amazonaws.com/prod/api"
    DEF_CLIENT="4ratjdjonqm17tln6bs2761ci3"   # fieldsight-web-client (pool ap-southeast-2_q88pd6XXr)
    ;;
  test)
    BUCKET="fieldsight-web-test-509194952652"
    CF_ID="E34AAK2PCGPWVZ"
    # derive the test API URL from the SAM stack output once it's deployed
    DEF_API="$(aws cloudformation describe-stacks --stack-name fieldsight-test --region "$REGION" \
                 --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text 2>/dev/null || true)"
    DEF_CLIENT=""   # set COGNITO_CLIENT_ID=… for the test pool
    ;;
  *) echo "stage must be test|prod"; exit 1 ;;
esac

API_BASE_URL="${API_BASE_URL:-$DEF_API}"
COGNITO_CLIENT_ID="${COGNITO_CLIENT_ID:-$DEF_CLIENT}"
COGNITO_HOSTED_UI_DOMAIN="${COGNITO_HOSTED_UI_DOMAIN:-}"

if [ -z "$API_BASE_URL" ]; then
  echo "❌ API_BASE_URL unknown for $STAGE (deploy the backend first, or pass API_BASE_URL=…)"; exit 1
fi

echo "Deploying ui/ → s3://$BUCKET  (CloudFront $CF_ID)"
echo "  API_BASE_URL      = $API_BASE_URL"
echo "  COGNITO_CLIENT_ID = ${COGNITO_CLIENT_ID:-<unset — login will not work until set>}"

cat > ui/scripts/env-config.js <<EOF
/* generated by deploy-ui.sh for ${STAGE} — do not commit */
window.FS_RUNTIME = {
  apiBaseUrl: "${API_BASE_URL}",
  cognitoClientId: "${COGNITO_CLIENT_ID}",
  cognitoHostedUiDomain: "${COGNITO_HOSTED_UI_DOMAIN}",
  useMocks: false
};
window.FS_COGNITO_CONFIG = {
  clientId: "${COGNITO_CLIENT_ID}",
  hostedUiDomain: "${COGNITO_HOSTED_UI_DOMAIN}"
};
EOF

aws s3 sync ui/ "s3://${BUCKET}/" --delete --region "$REGION" \
  --exclude ".git/*" --exclude ".vscode/*" --exclude "*.md"

aws cloudfront create-invalidation --distribution-id "$CF_ID" --paths "/*" \
  --query 'Invalidation.{Id:Id,Status:Status}' --output table

echo "✅ UI deployed to ${STAGE}. (CloudFront invalidation may take a minute.)"
