"""Shared, dependency-free text -> literal-term extraction.

Split out of lambda_ask_agent.py (where `_lexical_terms` originated, driving
`_aggregate_topics`' title-substring ranking) so that lambda_rag_search.py can
use the SAME extraction to build the keyword arm's tsquery (2026-09-22 fix:
"the keyword arm can actually fire"). Both lambdas import this module rather
than one importing the other's file -- lambda_ask_agent.py pulls in boto3
clients, S3 config, and several sibling modules (batch_stitch,
deletion_mirror, transcript_utils) at import time that lambda_rag_search.py
(in-VPC, no internet egress, BUG-36) has no business depending on.

Pure functions only: no psycopg, no boto3, no I/O.
"""
import re

# Latin/digit runs, and the scripts written without spaces between words (CJK
# ideographs and kana). They need different handling, which is the whole point:
# splitting on `[^a-z0-9]+` produced NO terms at all for a Chinese question, so
# no row could ever be `lexical`, the lexical-first ordering did nothing, and
# only rows inside _NO_LEX_MAX_DIST survived. The same question asked in Chinese
# returned strictly less than in English, and sometimes nothing.
_LATIN_RUN = re.compile(r"[a-z0-9]+")
_UNSPACED_RUN = re.compile(r"[㐀-䶿一-鿿぀-ヿ豈-﫿]+")
# A token mixing letters and digits is an identifier — "b2", "k1", "sb1108" —
# and the 3-character floor was dropping exactly the zone and grid references
# people search for, in English as much as in Chinese.
_IDENTIFIER = re.compile(r"[a-z]\d|\d[a-z]")


def lexical_terms(question):
    """Terms for the literal-containment half of the hybrid ranking, and
    (2026-09-22) the source of the keyword arm's OR query in lambda_rag_search.

    Latin runs keep the 3-character floor, which exists so "we"/"is"/"of" do not
    make every row lexical; an identifier is exempt from it.

    A run of an unspaced script becomes overlapping 2-character shingles rather
    than one long token: "钢筋合格证" as a whole almost never appears verbatim in
    a title, while "钢筋" does. Standard cheap approach, and it leaves the
    ranking design untouched — Chinese simply gets to participate in it.

    Other scripts (Cyrillic, Greek, …) yield no terms, exactly as today.
    Shingling a space-separated script would over-match, and no product language
    needs it yet.
    """
    q = (question or "").lower()
    terms = [t for t in _LATIN_RUN.findall(q)
             if len(t) >= 3 or _IDENTIFIER.search(t)]
    for run in _UNSPACED_RUN.findall(q):
        terms.extend(run[i:i + 2] for i in range(len(run) - 1))
    return terms


# English stopwords, for the QUERY path only (query_terms(), below) -- NOT
# used by lexical_terms() itself, which _aggregate_topics' title-substring
# ranking in lambda_ask_agent.py also depends on (existing tests, including
# two Chinese ones, pin lexical_terms()'s current behavior; see
# test_lambda_ask_agent_search.py). Changing lexical_terms() to drop
# stopwords would change that ranking's admission rule too, for no reason
# related to the bug being fixed here, so this is a second, narrower function
# instead of a change to the shared one.
#
# 2026-09-22 second fix ("the keyword arm can actually fire", round 2): the
# controller ran the owner's REAL sentence 'when did request ps4? and why?'
# through the real path and measured three unrelated chunks matching, because
# lexical_terms() only floors terms at 3 characters and has no stopword
# filter -- 'when'/'did'/'and'/'why' all clear that floor, and OR'd together
# in the keyword arm's tsquery, ONE of them alone matches nearly every chunk
# in a corpus (the 'simple' half of migration 0061's combined tsvector does
# not drop stopwords either -- that is the whole point of 'simple').
#
# SOURCE: a word is an English stopword exactly when Postgres's own
# `to_tsvector('english', word)` yields nothing for it -- not a hand-picked
# or borrowed (e.g. NLTK) list, which would not necessarily agree with what
# the 'english' text-search config this repo actually queries against
# considers a stopword. This list was generated by running EVERY word below
# through a real local Postgres (`to_tsvector('english', word) == ''`) and
# keeping only the ones that came back empty -- see
# tests/integration/test_literal_token_search_sql.py::
# test_every_query_stopword_is_actually_dropped_by_to_tsvector, which pins
# this exact set against a real Postgres so it cannot silently drift from its
# authority. This module is pure (no psycopg/boto3/I/O -- see module
# docstring), so the list has to be shipped as a constant; the integration
# test is what keeps the constant honest.
QUERY_STOPWORDS = frozenset({
    "a", "about", "above", "after", "again", "against", "all", "am", "an",
    "and", "any", "are", "as", "at", "be", "because", "been", "before",
    "being", "below", "between", "both", "but", "by", "can", "did", "do",
    "does", "doing", "down", "during", "each", "few", "for", "from",
    "further", "had", "has", "have", "having", "he", "her", "here", "hers",
    "herself", "him", "himself", "his", "how", "i", "if", "in", "into",
    "is", "it", "its", "itself", "just", "me", "more", "most", "my",
    "myself", "nor", "not", "now", "of", "off", "on", "once", "only", "or",
    "other", "our", "ours", "ourselves", "out", "over", "own", "same",
    "she", "should", "so", "some", "such", "than", "that", "the", "their",
    "theirs", "them", "themselves", "then", "there", "these", "they",
    "this", "those", "through", "to", "too", "under", "until", "up",
    "very", "was", "we", "were", "what", "when", "where", "which", "while",
    "who", "whom", "why", "will", "with", "you", "your", "yours",
    "yourself", "yourselves",
})


def query_terms(question):
    """lexical_terms(), minus English stopwords -- the extraction the keyword
    arm's OR query (or_query, below) must be built from, NOT lexical_terms()
    itself. lexical_terms()'s 3-character floor lets 'when'/'did'/'and'/'why'/
    'was' through (they are all >= 3 characters), and none of them are
    identifier-shaped enough to need the exemption either. OR'd together in a
    tsquery, a single stopword like 'and' matches nearly every chunk in the
    corpus -- MEASURED on a real Postgres, 2026-09-22: the sentence
    'when did request ps4? and why?' matched three chunks about bathroom
    tile, Twizel booking, and a concrete pour, none related to the question.

    An identifier that also happens to collide with a stopword spelling
    cannot occur here in practice: every word in QUERY_STOPWORDS is pure
    alphabetic, and lexical_terms()'s _IDENTIFIER exemption only ever fires
    on a token mixing a letter and a digit -- disjoint by construction, so
    this filter never has to choose between the two.

    If filtering removes every term, the caller gets []; or_query([]) == ""
    keeps the keyword arm inert rather than match-all -- the same property
    lexical_terms() -> or_query already had, just measured against a real
    sentence this time instead of a bare token.
    """
    return [t for t in lexical_terms(question) if t not in QUERY_STOPWORDS]


def or_query(terms):
    """Join extracted terms into ONE `websearch_to_tsquery` input string that
    parses as an OR, not an AND -- the fix for Cause A of "the keyword arm can
    actually fire" (2026-09-22): binding the caller's whole question as
    `%(q_text)s` made `websearch_to_tsquery` AND every non-stopword term
    together, which a natural-language question essentially never satisfies.

    Measured: `websearch_to_tsquery('simple', 'ps4 or light or pole')` ->
    `'ps4' | 'light' | 'pole'`. `lexical_terms` only ever emits lowercase
    alnum runs (no spaces, no quotes, no literal "or"), so the terms are safe
    to join with the bare word `or` and no further escaping.

    An empty term list returns "" -- `websearch_to_tsquery('simple', '')` is
    an empty tsquery that matches NOTHING, never everything. This is the
    property `test_a_conceptual_query_with_no_literal_terms_is_unaffected`
    (and lambda_rag_search's own tests) depend on: a question with no literal
    terms must leave the keyword arm inert, not turn it into a match-all.
    """
    return " or ".join(terms)
