"""The global base set, as Python, so the tagger and the database agree.

THE SAME VOCABULARY LIVES IN TWO PLACES AND THAT IS A PROBLEM THIS FILE OWNS.
`src/migrations/0065_taxonomy.sql` seeds these rows into Aurora; this module is
what `lambda_extract_session` uses, because that lambda runs OUTSIDE the VPC --
it can reach the model and cannot reach the database. A second copy is how a
feature ends up labelling topics with words the database does not have.

So the copies are held together mechanically:
tests/unit/test_the_base_set_is_one_vocabulary.py parses the migration and
asserts it matches this list exactly -- every slug, every label, every parent,
every sort order. Edit one without the other and that test fails.

WHAT THIS DOES NOT COVER: a company's own tags, and a project's own children.
Those live only in Aurora and this lambda cannot see them, so the extraction-
time tagger works from the base set alone -- which is exactly the vocabulary
the bake-off measured. Tagging with a company's extensions needs the request/
response shape the programme matcher already uses (an in-VPC writer emits an
artifact, a non-VPC lambda answers it), and that is a later batch, not a thing
to bolt on here.
"""

#: [{slug, label, parent, parent_slug, sort_order}] -- the 70 leaves. Parents
#: are not in this list: nothing is tagged with a level-1 word, they exist to
#: group and to read.
LEAVES = [
    {"slug": "structure.foundations", "label": "Foundations",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 10},
    {"slug": "structure.slab", "label": "Slab",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 20},
    {"slug": "structure.framing", "label": "Framing",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 30},
    {"slug": "structure.steelwork", "label": "Steelwork",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 40},
    {"slug": "structure.concrete", "label": "Concrete",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 50},
    {"slug": "structure.precast", "label": "Precast",
     "parent": "Structure", "parent_slug": "structure", "sort_order": 60},
    {"slug": "architecture.walls", "label": "Walls",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 10},
    {"slug": "architecture.ceilings", "label": "Ceilings",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 20},
    {"slug": "architecture.floorings", "label": "Floorings",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 30},
    {"slug": "architecture.roofing", "label": "Roofing",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 40},
    {"slug": "architecture.windows-and-doors", "label": "Windows & doors",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 50},
    {"slug": "architecture.joinery", "label": "Joinery",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 60},
    {"slug": "architecture.cladding", "label": "Cladding",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 70},
    {"slug": "architecture.stairs", "label": "Stairs & balustrades",
     "parent": "Architecture", "parent_slug": "architecture", "sort_order": 80},
    {"slug": "envelope.waterproofing", "label": "Waterproofing",
     "parent": "Envelope & weathertightness", "parent_slug": "envelope", "sort_order": 10},
    {"slug": "envelope.insulation", "label": "Insulation",
     "parent": "Envelope & weathertightness", "parent_slug": "envelope", "sort_order": 20},
    {"slug": "envelope.air-barrier", "label": "Air barrier",
     "parent": "Envelope & weathertightness", "parent_slug": "envelope", "sort_order": 30},
    {"slug": "envelope.glazing-seals", "label": "Glazing & seals",
     "parent": "Envelope & weathertightness", "parent_slug": "envelope", "sort_order": 40},
    {"slug": "envelope.external-drainage", "label": "External drainage",
     "parent": "Envelope & weathertightness", "parent_slug": "envelope", "sort_order": 50},
    {"slug": "mechanical.hvac", "label": "HVAC",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 10},
    {"slug": "mechanical.ductwork", "label": "Ductwork",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 20},
    {"slug": "mechanical.plumbing", "label": "Plumbing",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 30},
    {"slug": "mechanical.drainage", "label": "Drainage",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 40},
    {"slug": "mechanical.fire-services", "label": "Fire services",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 50},
    {"slug": "mechanical.lifts", "label": "Lifts",
     "parent": "Mechanical", "parent_slug": "mechanical", "sort_order": 60},
    {"slug": "electrical.power", "label": "Power",
     "parent": "Electrical", "parent_slug": "electrical", "sort_order": 10},
    {"slug": "electrical.lighting", "label": "Lighting",
     "parent": "Electrical", "parent_slug": "electrical", "sort_order": 20},
    {"slug": "electrical.data-comms", "label": "Data & comms",
     "parent": "Electrical", "parent_slug": "electrical", "sort_order": 30},
    {"slug": "electrical.switchboard", "label": "Switchboard",
     "parent": "Electrical", "parent_slug": "electrical", "sort_order": 40},
    {"slug": "electrical.security-and-access", "label": "Security & access",
     "parent": "Electrical", "parent_slug": "electrical", "sort_order": 50},
    {"slug": "finishes.plastering", "label": "Plastering",
     "parent": "Finishes", "parent_slug": "finishes", "sort_order": 10},
    {"slug": "finishes.painting", "label": "Painting",
     "parent": "Finishes", "parent_slug": "finishes", "sort_order": 20},
    {"slug": "finishes.tiling", "label": "Tiling",
     "parent": "Finishes", "parent_slug": "finishes", "sort_order": 30},
    {"slug": "finishes.floor-finish", "label": "Floor finish",
     "parent": "Finishes", "parent_slug": "finishes", "sort_order": 40},
    {"slug": "finishes.fixtures-and-fittings", "label": "Fixtures & fittings",
     "parent": "Finishes", "parent_slug": "finishes", "sort_order": 50},
    {"slug": "sitework.earthworks", "label": "Earthworks",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 10},
    {"slug": "sitework.excavation", "label": "Excavation",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 20},
    {"slug": "sitework.services-trenching", "label": "Services trenching",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 30},
    {"slug": "sitework.paving", "label": "Paving",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 40},
    {"slug": "sitework.landscaping", "label": "Landscaping",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 50},
    {"slug": "sitework.temporary-works", "label": "Temporary works",
     "parent": "Sitework & civil", "parent_slug": "sitework", "sort_order": 60},
    {"slug": "quality.defect", "label": "Defect",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 10},
    {"slug": "quality.rework", "label": "Rework",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 20},
    {"slug": "quality.inspection", "label": "Inspection",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 30},
    {"slug": "quality.test-and-commissioning", "label": "Test & commissioning",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 40},
    {"slug": "quality.consent-and-code", "label": "Consent & code",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 50},
    {"slug": "quality.as-built", "label": "As-built",
     "parent": "Quality & compliance", "parent_slug": "quality", "sort_order": 60},
    {"slug": "safety.hazard", "label": "Hazard",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 10},
    {"slug": "safety.incident-or-near-miss", "label": "Incident / near miss",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 20},
    {"slug": "safety.ppe", "label": "PPE",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 30},
    {"slug": "safety.permit-and-isolation", "label": "Permit & isolation",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 40},
    {"slug": "safety.traffic-management", "label": "Traffic management",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 50},
    {"slug": "safety.induction", "label": "Induction",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 60},
    {"slug": "safety.emergency-preparedness", "label": "Emergency preparedness",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 70},
    {"slug": "safety.method-statement", "label": "Method statement / TA",
     "parent": "Safety", "parent_slug": "safety", "sort_order": 80},
    {"slug": "commercial.variation", "label": "Variation",
     "parent": "Commercial", "parent_slug": "commercial", "sort_order": 10},
    {"slug": "commercial.cost-and-pricing", "label": "Cost & pricing",
     "parent": "Commercial", "parent_slug": "commercial", "sort_order": 20},
    {"slug": "commercial.claim-and-payment", "label": "Claim & payment",
     "parent": "Commercial", "parent_slug": "commercial", "sort_order": 30},
    {"slug": "commercial.contract-and-scope", "label": "Contract & scope",
     "parent": "Commercial", "parent_slug": "commercial", "sort_order": 40},
    {"slug": "commercial.procurement", "label": "Procurement",
     "parent": "Commercial", "parent_slug": "commercial", "sort_order": 50},
    {"slug": "programme.schedule", "label": "Schedule",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 10},
    {"slug": "programme.delay-and-disruption", "label": "Delay & disruption",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 20},
    {"slug": "programme.delivery-and-materials", "label": "Delivery & materials",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 30},
    {"slug": "programme.plant-and-equipment", "label": "Plant & equipment",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 40},
    {"slug": "programme.access-and-sequencing", "label": "Access & sequencing",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 50},
    {"slug": "programme.labour", "label": "Labour",
     "parent": "Programme & logistics", "parent_slug": "programme", "sort_order": 60},
    {"slug": "stakeholders.client", "label": "Client",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 10},
    {"slug": "stakeholders.consultant", "label": "Consultant & designer",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 20},
    {"slug": "stakeholders.subcontractor", "label": "Subcontractor",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 30},
    {"slug": "stakeholders.supplier", "label": "Supplier",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 40},
    {"slug": "stakeholders.council", "label": "Council & inspector",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 50},
    {"slug": "stakeholders.neighbour", "label": "Neighbour & public",
     "parent": "Stakeholders", "parent_slug": "stakeholders", "sort_order": 60},
]

#: {slug: label} for the twelve level-1 groups, in their own order.
PARENTS = [
    {"slug": "structure", "label": "Structure", "sort_order": 10},
    {"slug": "architecture", "label": "Architecture", "sort_order": 20},
    {"slug": "envelope", "label": "Envelope & weathertightness", "sort_order": 30},
    {"slug": "mechanical", "label": "Mechanical", "sort_order": 40},
    {"slug": "electrical", "label": "Electrical", "sort_order": 50},
    {"slug": "finishes", "label": "Finishes", "sort_order": 60},
    {"slug": "sitework", "label": "Sitework & civil", "sort_order": 70},
    {"slug": "quality", "label": "Quality & compliance", "sort_order": 80},
    {"slug": "safety", "label": "Safety", "sort_order": 90},
    {"slug": "commercial", "label": "Commercial", "sort_order": 100},
    {"slug": "programme", "label": "Programme & logistics", "sort_order": 110},
    {"slug": "stakeholders", "label": "Stakeholders", "sort_order": 120},
]

SLUGS = frozenset(l["slug"] for l in LEAVES)
