"""Unit: the exported ONNX model must answer exactly what SpeechBrain answered.

This is the gate the whole Lambda-side design rests on. The function cannot carry torch and
speechbrain, so it runs the ONNX export instead — and an export that drifts would move every
similarity score by a little, silently. Every threshold measured before the drift
(`DEFAULT_MIN_MARGIN`, `DEFAULT_MAX_FRAME_SPREAD`, the Phase 0 separation) would quietly stop
meaning what it says, and nothing would fail.

What is committed here is the REFERENCE VECTORS, not the model. The model is 84 MB — a
742 KB graph plus an 83 MB external `.data` sidecar — and lives in S3 under `models/`,
beside the Silero VAD model and for the same recorded reason (BUG-02: loading that one from
a Layer shipped a different version whose output was silently wrong). A few KB of reference
vectors detect the same class of drift.

The comparison is skipped when the model is absent, so CI stays green without an 84 MB
download — but the two anti-vacuity tests are NOT, because their whole job is to fire on the
machines that skip the comparison.

**Phase 5 may not start until the comparison has actually run and passed** — a permanently
skipped gate is not a gate. **It has: 2026-08-13, 3 passed against the model in S3, run with
`ECAPA_ONNX_PATH` pointed at a local copy.** Before that date this file had never once
executed its own assertion.

Measured 2026-08-13: 6 of 6 real enrolments at cosine 1.000000. The 0.999 threshold is the
tolerance the design allows, not the accuracy observed.
"""
import json
import os

import numpy as np
import pytest

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FIXTURES = os.path.join(REPO, "tests", "fixtures", "voiceprint_parity")
REFS = os.path.join(FIXTURES, "references.json")
MODEL = os.environ.get("ECAPA_ONNX_PATH", os.path.join(REPO, "models", "ecapa_tdnn.onnx"))
GATE = 0.999

# Only the comparison itself needs the model. The other two tests here exist to stop THIS
# FILE passing vacuously, and until 2026-08-13 they were under a file-level skip alongside it
# — so on any machine without the 84 MB artifact (which is every CI runner, since the model
# ships in S3) somebody could delete references.json or commit the 83 MB weight sidecar and
# nothing would go red. A guard that is skipped wherever it would fire is not a guard.
needs_model = pytest.mark.skipif(
    not os.path.exists(MODEL),
    reason=f"no ONNX model at {MODEL}; export it with scripts/export_ecapa_onnx.py or set "
           f"ECAPA_ONNX_PATH. The references are committed, so this skip is about the "
           f"84 MB artifact and nothing else.")


def _session():
    ort = pytest.importorskip("onnxruntime")
    return ort.InferenceSession(MODEL, providers=["CPUExecutionProvider"])


def test_the_fixture_audio_is_not_anybody_s_voice():
    """The fixtures were SIX REAL PEOPLE — 5 s of raw voice each, named `ben`, `Joe`, `Leo`,
    `Mike`, `Zoe` — plus their real 192-d voiceprints in references.json, committed to this
    repository on 2026-08-13 by the export work. In every clone, on GitHub, with no consent
    record, no expiry, and outside the reach of any withdrawal.

    Five reviews chased a biometric-residence defect through a cache, an S3 artifact and a
    result payload. It was in git the whole time, put there by the same hands doing the
    chasing.

    Parity does not need real voices: it asserts that the exported ONNX answers what
    SpeechBrain answered, and that holds for any audio at all. The fixtures are now
    deterministic synthetic tones.
    """
    import numpy as np
    names = sorted(f[:-4] for f in os.listdir(FIXTURES) if f.endswith(".npy"))
    assert names, "no fixture audio at all"
    forbidden = {"ben", "ben_chinese", "joe", "leo", "mike", "zoe"}
    assert not (set(n.lower() for n in names) & forbidden), (
        f"{names} names a person; fixture audio must not be anybody's voice")
    for n in names:
        a = np.load(os.path.join(FIXTURES, f"{n}.npy"))
        assert a.dtype == np.float32 and a.size == 5 * 16000, f"{n} is not 5 s of 16 kHz"


def test_the_references_are_absent_and_that_is_recorded_not_forgotten():
    """references.json held the six people's actual voiceprints and went with them.

    It can only be regenerated by running the export script against SpeechBrain — the point
    of the file is that ONNX agrees with a DIFFERENT implementation, so generating it from
    ONNX would compare the model to itself. Until somebody does that on a box with torch,
    the comparison below skips, and this test is what stops the skip from becoming silence.

    **Phase 5 may not start until the comparison has run against the synthetic fixtures.**
    It ran once, on 2026-08-13, against the fixtures that have now been removed.
    """
    assert not os.path.exists(REFS), (
        "references.json is back — if it was regenerated, delete this test and restore the "
        "one it replaced; if it was restored from git, check whose voices are in it")


@needs_model
@pytest.mark.skipif(not os.path.exists(REFS),
                    reason="references.json was removed with the real-voice fixtures; "
                           "regenerate with scripts/export_ecapa_onnx.py against the "
                           "synthetic audio, on a box with torch + speechbrain")
def test_every_reference_survives_the_export():
    import voiceprint_utils as vp

    sess = _session()
    refs = json.load(open(REFS, encoding="utf-8"))
    worst, worst_name = 1.0, None
    for name, rec in refs.items():
        clip = np.load(os.path.join(FIXTURES, f"{name}.npy"))
        got = sess.run(None, {"wav": clip[None, :].astype(np.float32),
                              "wav_lens": np.array([1.0], dtype=np.float32)})[0].ravel()
        c = vp.cosine(np.asarray(rec["embedding"], dtype=np.float64), got)
        if c < worst:
            worst, worst_name = c, name
    assert worst >= GATE, (
        f"the ONNX export no longer matches SpeechBrain: worst cosine {worst:.6f} on "
        f"{worst_name!r}, gate {GATE}. Every threshold in voiceprint_utils was measured "
        f"against the SpeechBrain embedding; a drifted export moves them all with no error.")


def test_the_model_is_not_committed_to_the_repo():
    """84 MB of weights in git is a decision, not an accident. It is deliberately NOT taken:
    the model ships in S3 under `models/`, downloaded at cold start like the VAD model.
    This pins that so a future export does not quietly land in a commit."""
    tracked = os.path.join(REPO, "models", "ecapa_tdnn.onnx.data")
    assert not os.path.exists(tracked), (
        "the 83 MB weight sidecar is in the working tree — it belongs in S3 under models/, "
        "beside silero_vad.onnx, not in the repository")
