"""Unit: an unknown site is unknown, not whichever customer SITE_NAME names.

`user_site_name = user_site_info.get('name', site_name)` with
`site_name = os.environ.get('SITE_NAME', 'Construction Site')`. Every user not
in the legacy `config/user_mapping.json` — which is every registration-era
account — therefore had their day filed under whatever that variable said.

Seen on TEST on 2026-09-10, in a report generated by the deployed code:

    "user_name": "Neil_Blunden",
    "site": "SB1108 Ellesmere College"

which is a different customer's site. BUG-41 recorded the general rule after
the same field sent RAG attribution to the wrong site:

    env 级默认值用于多租户归属是危险设计 —— 它把"查不到"静默变成"归到某个具体客户"

The fix there was applied to what ingest *consumes* (it prefers
`recordings.site_for_day` now); the report still displayed and carried the wrong
name. Empty is the honest answer and the safer one: `resolve_site` skips the
name lookup entirely and falls through to membership, which is where the answer
actually is.
"""
import pytest

# Plain import, not importorskip. `lambda_report_generator` imports cleanly in
# this suite -- 40 other test modules import it the same way -- and a skip here
# would turn "the module stopped being importable" into seven silently green
# tests guarding a customer-facing attribution field.
import lambda_report_generator as rg


def test_a_known_site_is_used():
    assert rg.site_name_for({"name": "UC PK"}) == "UC PK"


@pytest.mark.parametrize("info", [None, {}, {"name": ""}, {"name": None}, "nonsense"])
def test_an_unknown_site_is_empty_not_borrowed(info, monkeypatch):
    """Whatever SITE_NAME happens to be set to, it is not this user's site."""
    monkeypatch.setenv("SITE_NAME", "SB1108 Ellesmere College")
    assert rg.site_name_for(info) == ""


def test_the_env_default_cannot_reach_a_report(monkeypatch):
    """The variable still exists for the deployment-wide title; it must not
    become an attribution."""
    monkeypatch.setenv("SITE_NAME", "Somebody Else's Site")
    assert "Somebody" not in rg.site_name_for({})
